namespace eyewearshop_data.Entities;

/// <summary>
/// Represents a payment attempt/transaction with an external gateway (e.g. MoMo, VietQR),
/// linked to an order. This is separate from the high-level Payment record used for
/// accounting and partial payments.
/// </summary>
public class PaymentTransaction
{
    public long PaymentTransactionId { get; set; }

    public long OrderId { get; set; }

    /// <summary>
    /// Name of the gateway provider, e.g. "MOMO", "VIETQR".
    /// </summary>
    public string Gateway { get; set; } = string.Empty;

    /// <summary>
    /// The transaction or reference id returned by the gateway.
    /// </summary>
    public string? GatewayTransactionId { get; set; }

    /// <summary>
    /// Id generated by our system per request (idempotency key).
    /// </summary>
    public string RequestId { get; set; } = string.Empty;

    public decimal Amount { get; set; }

    public string Currency { get; set; } = "VND";

    /// <summary>
    /// 0 = Pending, 1 = Succeeded, 2 = Failed, 3 = Cancelled, 4 = Expired
    /// </summary>
    public short Status { get; set; } = 0;

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public DateTime? PaidAt { get; set; }

    /// <summary>
    /// Optional raw JSON of the last request we sent to the gateway (for troubleshooting).
    /// </summary>
    public string? RawRequest { get; set; }

    /// <summary>
    /// Optional raw JSON of the last response / webhook payload (for troubleshooting).
    /// </summary>
    public string? RawResponse { get; set; }

    public Order Order { get; set; } = null!;
}

